"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from "react";
import { env } from "@/env/schema";
import { usePathname, useRouter } from "next/navigation";
import Navbar from "@/components/composite/Navbar";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter()
  const pathname = usePathname()
  const checkAuth = async () => {
    console.log("checking auth")
    const res = await fetch(`${env.NEXT_PUBLIC_API_URL}/auth/check`, {
      credentials: 'include',
    })
    if (res.status !== 200) {
      router.push("/login")
    } else {
      await checkOrg()
    }
  }

  const checkOrg = async () => {
    const res = await fetch(`${env.NEXT_PUBLIC_API_URL}/orgs/check`, {
      credentials: 'include',
    })
    if (res.status !== 200) {
      router.push("/org/select")
    }
  }


  useEffect(() => {
    checkAuth()
  }, [pathname])

  const noNavbarPath = ["/login", "/org/select"]
  const isNavbarRoute = noNavbarPath.findIndex(ele => pathname.startsWith(ele)) === -1

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-w-[100vw] flex">
          {isNavbarRoute && < Navbar />}

          <div className="flex justify-center w-full">
            <div className="md:w-[80%] p-10">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
