"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect, useState } from "react";
import { env } from "@/env/schema";
import { useRouter } from "next/navigation";
import Navbar from "@/components/composite/Navbar";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter()

  const checkAuth = async () => {
    console.log("checking auth")
    const res = await fetch(`${env.NEXT_PUBLIC_API_URL}/auth/check`, {
      credentials: 'include',
    })
    if (res.status !== 200) {
      router.push("/login")
    } else {
      await checkOrg()
    }
  }

  const checkOrg = async () => {
    const res = await fetch(`${env.NEXT_PUBLIC_API_URL}/orgs/check`, {
      credentials: 'include',
    })
    if (res.status !== 200) {
      router.push("/org/select")
    }
  }


  useEffect(() => {
    checkAuth()
  }, [])


  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-w-[100vw] flex">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
